### ISSUE TITLE
[Enhancement] Option to get XP from placing blocks

### ISSUE THREAD

**Issue by jengendler** [gosvoh/GetExpForEverything#2]
For people who love spending their time building, it would be amazing to have an option to get XP from placing blocks. While it may not be for everyone, it could be something that's off by default, and perhaps a similar blacklist/whitelist feature to that of breaking blocks.

Thanks for making a great mod!

**Comment by gosvoh** [comment]
Added in https://github.com/gosvoh/GetExpForEverything/commit/b33723d3a07749468e900826fa9c38502f722c7a
